{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "polygon.fullname" . }}-bor
{{- range $key, $value := .Values.persistence.annotations }}
  {{ $key }}: {{ $value }}
{{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}